/*
389. Find the difference
You are given two strings s and t.

String t is generated by random shuffling string s and then add one more letter at a random position.

Return the letter that was added to t.



Example 1:

Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.

Example 2:

Input: s = "", t = "y"
Output: "y"



Constraints:

    0 <= s.length <= 1000
    t.length == s.length + 1
    s and t consist of lowercase English letters.

*/
class Solution {
public:
    char findTheDifference(string s, string t) {

        int tSum = 0;
        int sSum = 0;
        for(int i = 0; i < t.size(); i++) {
            tSum += t[i];
        }
        for(int j = 0; j < s.size(); j++) {
            sSum += s[j];
        }
        char ch = tSum - sSum;
        return ch;
    }
};
